-- 1. Create branches table
create table if not exists public.branches (
    id text primary key,
    name text not null,
    created_at timestamptz default now(),
    is_active boolean default true
);

-- 2. Create profiles table (linked to auth.users)
create table if not exists public.profiles (
    id uuid primary key references auth.users(id) on delete cascade,
    email text not null,
    branch_id text references public.branches(id) on delete set null,
    branch_name text,
    role text not null default 'TELLER',
    created_at timestamptz default now()
);

-- 3. Create branch_status table
create table if not exists public.branch_status (
    branch_id text primary key references public.branches(id) on delete cascade,
    status text not null default 'CLOSED',
    updated_at timestamptz default now()
);

-- 4. Create clients table
create table if not exists public.clients (
    id uuid primary key,
    "nationalId" text not null,
    "firstName" text not null,
    "lastName" text default '.',
    phone text,
    "branchId" text not null references public.branches(id) on delete cascade,
    "createdByUserId" uuid not null,
    status text not null default 'ACTIVE',
    "createdAt" timestamptz default now(),
    address text,
    nic_image text,
    signature_image text
);

-- 5. Create pawns table
create table if not exists public.pawns (
    id uuid primary key,
    client_id uuid not null references public.clients(id) on delete cascade,
    description text not null,
    appraised_value numeric(12, 2) not null default 0.00,
    disbursed_amount numeric(12, 2) not null default 0.00,
    branch_id text not null references public.branches(id) on delete cascade,
    created_by_user_id uuid not null,
    status text not null default 'PENDING_APPROVAL',
    created_at timestamptz default now(),
    approved_by text,
    approved_at timestamptz,
    redeemed_at timestamptz,
    redeem_amount numeric(12, 2),
    redeem_interest numeric(12, 2),
    redeemed_by text
);

-- 6. Create vault_transfer table
create table if not exists public.vault_transfer (
    id text primary key,
    date date not null,
    time text not null,
    from_vault text not null,
    to_vault text not null,
    amount numeric(12, 2) not null,
    currency text,
    status text not null default 'Pending',
    initiated_by text not null,
    notes text,
    approved_by text
);

-- 7. Create journal_entry table
create table if not exists public.journal_entry (
    id text primary key,
    date date not null,
    description text,
    reference text,
    total_debit numeric(12, 2) not null default 0.00,
    total_credit numeric(12, 2) not null default 0.00,
    created_by text not null,
    created_at timestamptz default now()
);

-- 8. Create journal_entry_line table
create table if not exists public.journal_entry_line (
    id bigint generated by default as identity primary key,
    journal_entry_id text not null references public.journal_entry(id) on delete cascade,
    account_name text not null,
    debit numeric(12, 2) not null default 0.00,
    credit numeric(12, 2) not null default 0.00
);

-- 9. Create account table
create table if not exists public.account (
    id text primary key,
    name text not null,
    type text not null,
    balance numeric(12, 2) not null default 0.00,
    interest_rate numeric(5, 2) not null default 0.00,
    status text not null default 'Active',
    opened_date timestamptz default now()
);

-- 10. Create stock_items table (for Pawning Stock Management)
create table if not exists public.stock_items (
    id uuid default gen_random_uuid() primary key,
    bill_no varchar not null,
    price numeric(12, 2) not null default 0.00,
    weight numeric(10, 3) not null default 0.000,
    date date not null,
    item_type varchar not null, -- PP, PR, NL, EAR, etc.
    status varchar not null default 'Active', -- 'Active', 'Withdrawn'
    branch_id text references public.branches(id) on delete cascade,
    withdrawal_date date,
    withdrawal_reason varchar,
    withdrawal_notes text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS) on all tables
alter table public.branches enable row level security;
alter table public.profiles enable row level security;
alter table public.branch_status enable row level security;
alter table public.clients enable row level security;
alter table public.pawns enable row level security;
alter table public.vault_transfer enable row level security;
alter table public.journal_entry enable row level security;
alter table public.journal_entry_line enable row level security;
alter table public.account enable row level security;
alter table public.stock_items enable row level security;

-- Create policies to allow all actions (dropping first if exists to prevent errors)

drop policy if exists "Public branches select" on public.branches;
drop policy if exists "Public branches insert" on public.branches;
drop policy if exists "Public branches update" on public.branches;
create policy "Public branches select" on public.branches for select using (true);
create policy "Public branches insert" on public.branches for insert with check (true);
create policy "Public branches update" on public.branches for update using (true);

drop policy if exists "Public profiles select" on public.profiles;
drop policy if exists "Public profiles insert" on public.profiles;
drop policy if exists "Public profiles update" on public.profiles;
create policy "Public profiles select" on public.profiles for select using (true);
create policy "Public profiles insert" on public.profiles for insert with check (true);
create policy "Public profiles update" on public.profiles for update using (true);

drop policy if exists "Public branch_status select" on public.branch_status;
drop policy if exists "Public branch_status insert" on public.branch_status;
drop policy if exists "Public branch_status update" on public.branch_status;
create policy "Public branch_status select" on public.branch_status for select using (true);
create policy "Public branch_status insert" on public.branch_status for insert with check (true);
create policy "Public branch_status update" on public.branch_status for update using (true);

drop policy if exists "Public clients select" on public.clients;
drop policy if exists "Public clients insert" on public.clients;
drop policy if exists "Public clients update" on public.clients;
create policy "Public clients select" on public.clients for select using (true);
create policy "Public clients insert" on public.clients for insert with check (true);
create policy "Public clients update" on public.clients for update using (true);

drop policy if exists "Public pawns select" on public.pawns;
drop policy if exists "Public pawns insert" on public.pawns;
drop policy if exists "Public pawns update" on public.pawns;
create policy "Public pawns select" on public.pawns for select using (true);
create policy "Public pawns insert" on public.pawns for insert with check (true);
create policy "Public pawns update" on public.pawns for update using (true);

drop policy if exists "Public vault_transfer select" on public.vault_transfer;
drop policy if exists "Public vault_transfer insert" on public.vault_transfer;
drop policy if exists "Public vault_transfer update" on public.vault_transfer;
create policy "Public vault_transfer select" on public.vault_transfer for select using (true);
create policy "Public vault_transfer insert" on public.vault_transfer for insert with check (true);
create policy "Public vault_transfer update" on public.vault_transfer for update using (true);

drop policy if exists "Public journal_entry select" on public.journal_entry;
drop policy if exists "Public journal_entry insert" on public.journal_entry;
drop policy if exists "Public journal_entry update" on public.journal_entry;
create policy "Public journal_entry select" on public.journal_entry for select using (true);
create policy "Public journal_entry insert" on public.journal_entry for insert with check (true);
create policy "Public journal_entry update" on public.journal_entry for update using (true);

drop policy if exists "Public journal_entry_line select" on public.journal_entry_line;
drop policy if exists "Public journal_entry_line insert" on public.journal_entry_line;
drop policy if exists "Public journal_entry_line update" on public.journal_entry_line;
create policy "Public journal_entry_line select" on public.journal_entry_line for select using (true);
create policy "Public journal_entry_line insert" on public.journal_entry_line for insert with check (true);
create policy "Public journal_entry_line update" on public.journal_entry_line for update using (true);

drop policy if exists "Public account select" on public.account;
drop policy if exists "Public account insert" on public.account;
drop policy if exists "Public account update" on public.account;
create policy "Public account select" on public.account for select using (true);
create policy "Public account insert" on public.account for insert with check (true);
create policy "Public account update" on public.account for update using (true);

drop policy if exists "Public stock_items select" on public.stock_items;
drop policy if exists "Public stock_items insert" on public.stock_items;
drop policy if exists "Public stock_items update" on public.stock_items;
create policy "Public stock_items select" on public.stock_items for select using (true);
create policy "Public stock_items insert" on public.stock_items for insert with check (true);
create policy "Public stock_items update" on public.stock_items for update using (true);
